# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sascha Gaudlitz
email: sascha.gaudlitz[AT]hu-berlin.de
#author:
#  social:
#    email: mailto:sascha.gaudlitz@hu-berlin.de

description: > # this means to ignore newlines until "baseurl:"
  Sascha Gaudlitz is a PhD student in Mathematical Statistics at Humboldt University Berlin. He is part of the Berlin-Oxford IRTG
  "Stochastic Analysis in Interaction" and is supervised by Markus Reiß.
#baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
#url: ""
#theme : jekyll-theme-hydejack
remote_theme: hydecorp/hydejack@v9.0.4

tagline: PhD Student

logo:                  /assets/logo.JPG

menu:
  - title:             Research
    url:               /research/
  - title:             Short CV
    url:               /shortcv/


# Sidebar image and theme color of the site.
accent_color:          rgb(102, 102, 255)
accent_image:          '/assets/img/Matterhorn5.jpg'

google fonds: false
# Build settings
markdown: kramdown

copyright:             © 2023. All rights reserved.

advertise:           true

# Make sure to exclude 'vendor' from the build
exclude: [vendor, "Gemfile", "Gemfile.lock"]

include:
  - .well-known
  - LICENSE.md
